adding:
  dependencies:
    config:
      - views.view.events
    module:
      - views
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_asle1hi593u2nvkj:
              uuid: ecb379fa-76c3-4fbd-a8a5-217f52a97d55
              region: main
              configuration:
                id: 'views_block:events-card_list'
                label: null
                label_display: null
                provider: views
                context_mapping: {  }
                views_label: ''
                items_per_page: none
                pager: some
                headline:
                  headline: Schedule
                  hide_headline: 0
                  heading_size: h2
                  headline_style: headline_bold_serif
                  headline_alignment: default
                  child_heading_size: h3
                exposed_filter_values: null
                layout_builder_styles: {  }
              weight: 5
              additional: {  }
              third_party_settings: {  }
removing: {  }
